stages:
    - build
    - test

build:
    stage: build
    image: alpine
    only:
        - master
    tags:
        - docker
    cache:
      paths:
        - ./*.cmake
        - CMakeCache.txt
    artifacts:
      paths:
        - 09arboles/test.cpp
    before_script:
        - apk add gcc g++ clang make cmake gtest
    script:
        - cmake ./
        - make