stages:
    - build
    - test

build:
    stage: build
    image: alpine
    tags:
        - docker
    cache:
      paths:
        - build
    artifacts:
      paths:
        - build/testArboles
    before_script:
        - apk add git python python3 gcc g++ clang make cmake
    script:
        - mkdir -p build
        - cd build
        - cmake ..
        - make

test arboles:
  stage: test
  tags:
    - docker
  script:
    - ls -lh build
    - build/testArboles